version: "2"

linters:
  # Use this section to enable specific linters.
  enable:
    - errcheck        # Check for unhandled errors
    - govet           # Go-related issues (e.g., shadowed variables)
    - gocritic        # Detect code issues like duplicate imports, etc.
    - gocyclo         # Cyclomatic complexity of functions
    - staticcheck     # Static code analysis
    - golint          # Style checking
    - ineffassign     # Detect unnecessary assignments
    - typecheck       # Type checking

  # Linter-specific settings.
  settings:
    gocritic:
      disabled-checks:
        - dupImport  # Disable duplicate import check (example)
    gocyclo:
      min-complexity: 15  # Function complexity threshold for gocyclo

run:
  timeout: 5m  # Timeout for linter runs
  tests: true  # Run the linter on test files as well

formatters:
  enable:
    - gofmt     # Formatting check
    - goimports # Imports sorting

  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'  # Use 'any' instead of 'interface{}' in the code
    goimports:
      local-prefixes:
        - github.com/mynextid/gid # Set the local import prefix to your repository